version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: ec-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: .
    container_name: ec-web
    environment:
      - PHP_IDE_CONFIG=serverName=${DDEV_PROJECT}.prod.site
      - COMPOSER_ALLOW_SUPERUSER=1
      - TZ=UTC
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
      - composer_cache:/root/.composer/cache
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: ec-db
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ec-pma
    environment:
      - PMA_HOST=db
      - PMA_USER=db
      - PMA_PASSWORD=db
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  dbdata:
  composer_cache:
