version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      
volumes:
  dbdata: